name: Delete feature branch
run-name: Delete {{ github.event.ref_type }} {{ github.event.ref }}

on:
  # Trigger this workflow on "delete" events, see
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#delete
  delete:

jobs:
  # Deletes the Azure resource group when the corresponding branch is deleted
  delete-feature-branch:
    runs-on: ubuntu-latest
    # Only run this job if the branch name starts with "feature"
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'feature')
    # Change this to your GitHub environment used to deploy the feature branches
    environment: Development
    permissions:
      # Required for wlgore/azure-repository-login
      id-token: write
    steps:
      - name: Azure login
        uses: wlgore/azure-repository-login@v1
        id: azure-login
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          location: EastUS
          bot-credentials: ${{ secrets.AZURE_REPOSITORY_LOGIN_BOT_CREDENTIALS }}
          environment: Development

      - name: Delete resource group
        run: |
          RG_NAME="${{ secrets.AZURE_TENANT_ID }} ${{ secrets.AZURE_SUBSCRIPTION_ID }} EastUS Development ${{ github.repository }} ${{ github.event.ref }}"
          RG_NAME="rg-arb-$(echo -n $RG_NAME | openssl sha1 | awk '{print $2}')"
          echo Deleting resource group "$RG_NAME"
          az group delete --name $RG_NAME --yes --no-wait
          echo Resource group "$RG_NAME" is now being deleted and should disappear shortly
